# 582-543-MO Traitement vidéo 

## Description du cours

* Techniques D’INTÉGRATION MULTIMÉDIA
* Département des techniques d’intégration multimédia
* 582.A1
* Pondération : 1-2-2
* Unités: 1,66
* Heures-contact : 45
* Session : 4

Ce cours permet à l’étudiante ou l’étudiant d’enregistrer, de modifier et de traiter des images en temps réel. 
L’étudiant sera appelé à appliquer des effets visuels aux images vidéo et à adapter les images en fonction de l’intégration.


## Objectifs 

### Intégrateur et ministériel
* 015J Traiter les images en mouvement

### Apprentissages
* Adapter l'image en mouvement  (Importance relative : 40% )
* Programmer des effets visuels interactifs  (Importance relative : 40% )
* Intégrer l'image en mouvement interactive à une production médiatique (Importance relative : 20% )


## Méthodologie 

L’approche pédagogique de ce cours emprunte à celle employée dans les séminaires de recherche-création en média numérique. Une attention particulière est attribuée au partage de l'expérimentation en lien avec le sujet du cours. Différentes activités pédagogiques seront à l'honneur, notamment :  

* Exposés magistraux
* Démonstrations 
* Séances de questions 
* Présentations étudiantes
* Valorisation des apprentissages autonomes
* Utilisation créative de logiciels
* Travaux pratiques itératifs  

## Développement

### Attitudes professionnelles
* Curiosité
* Capacité de partage 
* Créativité
* Esprit critique
* Sens esthétique 


### Habiletés transdisciplinaires
* Profil **technologies de l'information et de la communication (TIC)**
* Les étudiantes et étudiants auront à exploiter les TIC de manière efficace et responsable. 
* Recherche, traitement et présentation de l’information.


## Préalables
### Préalable absolu au présent cours :
* 582 413 MO Montage vidéo 

### Préalable absolu aux cours suivants :
* 582 513 MO Conception de projet multimédia
* 582 66B MO Expérience multimédia interactive
* 582 66G MO Production Web en entreprise

## Contexte particulier d’apprentissage 
* À distance; synchrone. 
* Possibilité d'utiliser le laboratoire informatique et le studio si nécessaire.

### Fiche technique
* Ordinateurs, projecteurs à haute luminosité ou télévision, haut-parleurs professionnels, casque audio,  matériel disponible pour TIM
* Logiciels de montage vidéo et traitemet vidéo en temps réel 
* Languages et protocoles de paramétrage  
* Technicienne ou technicien en travaux pratiques


## Contenus essentiels {#contenus_essentiels}

### Survol historique
* [Évolution historique du traitement vidéo dans les différentes formes d’art](#evolution_historique)
	* [Performance](#evolution_historique_performance) 
	* [Installation](#evolution_historique_installation)
	* [Évolution des technologies associées](#evolution_historique_technologies)
* [Langages et moyens expressifs de l’image en mouvement](#evolution_historique_language) 


### Fondements techniques 
* [Formats de fichiers](#lexique_fichiers) 
* [Encodage des vidéos](#lexique_encodage)  
* [Captation vidéo en temps réel](#aquerir_captation) 
* [Logiciels de traitement vidéo en temps réel et d’interactivité](#traiter_logiciels) 
* [Logiciels de programmation nodale](#programmer_logiciels) 
* Notions de traitement vidéo 
	* pixels
	* couleurs 
	* texture
	* matrice 
	* mémoire tampon 
	* alpha channel 
	* rendu OpenGL

### Traitement de l'image en mouvement
* Usage de capture vidéo en temps réel  
* Effets visuels et filtres applicables en temps réel sur des matériaux visuels  
* Traitement visuel en temps réel à l’aide d’effets et de logiciels de programmation multimédia et nodale 
* Flot de données entre les objets du logiciel 
* Exploitation des fonctions des logiciels de traitement vidéo en temps réel 
* Utilisation de nuanceurs (shaders) 

### Programmation d'effets visuels 
* Programmation de compositions visuelles génératives 
* Réalisation d’un échantillonneur/mélangeur visuel 
* Programmation pour contrôler la lecture vidéo, 
	* montage temps réel 
	* niveau des couleurs 
	* alpha channel  
* Programmation nodale pour créer des effets en temps réel 
	* position
	* rotation
	* dimensions
	* mixage d’images 
	* incrustation 
	* distorsion 
	* délais
	* rétroaction (feedback)
	* modification de couleurs 
	* chromakey 
	* lumière 
	* fumée
	* texture
* Nuanceurs (shaders) : vertex, pixel et géométrie 


### Image en mouvement et interactivité 
* Intégration des composantes dans une production interactive 
* Configuration logicielle et matérielle d’une production interactive  
* Conceptualisation et scénarisation d’un projet visuel interactif  
* Captation de mouvement et de présence
* Programmation de la captation de mouvement et de présence 
* Utilisation d’interfaces de contrôle interactives 
* Utilisation d’OSC, MIDI, DMX ou ArtNet pour interagir avec d'autres logiciels et interfaces de contrôle


### Gestion de projets
* Schématisation 
* Prototypage 
* Gestion de banques d’images 
* Optimisation des performances de l’application 
* Test de contrôle de qualité 
* Préréglages 
* Optimisation de la programmation et commentaires 
* Console de débogage 
* Exportation de projets 
* Formats de sauvegarde  
* Application autonome 
* Sauvegarde et archivage des médias 
* Ajustement des effets visuels en fonction des tests 