# Lexique technique et technologique{#lexique}

## Composantes du signal vidéo
### Signaux de transmission
* [Signaux analogues/digitaux](https://en.wikipedia.org/wiki/Video#Analog_video)
	* [transmission télévisuelle analogue](https://en.wikipedia.org/wiki/Analog_television)

### résolutions

* [résolutions](https://en.wikipedia.org/wiki/Computer_display_standard#/media/File:Vector_Video_Standards2.svg)

### Ratio
* [ratios image](https://en.wikipedia.org/wiki/Display_aspect_ratio)
* [ratios-pixels](https://en.wikipedia.org/wiki/Pixel_aspect_ratio)

### Débit
* [Débit (bitrate)](https://en.wikipedia.org/wiki/Bit_rate#Video) 

### Échantillonnage
* Profondeur de l'échantillonnage couleur 
	* [bit/canal](https://en.wikipedia.org/wiki/Color_depth)  
* [chroma subsampling](https://en.wikipedia.org/wiki/Chroma_subsampling#Sampling_systems_and_ratios) 
	* [4:4:4 vs 4:2:2 vs 4:2:0](https://upload.wikimedia.org/wikipedia/commons/0/06/Colorcomp.jpg)
	* [4:4:4 vs 4:4:4:4](https://en.wikipedia.org/wiki/Alpha_compositing)

### Cadence
* [Cadence](https://frames-per-second.appspot.com) 

### Trame
* [Trame (progressif/entrelacé)](https://web.archive.org/web/20140222010640/http://neuron2.net/LVG/interlacing.html)

### Poid
* [calcul de grosseur de fichier](https://toolstud.io/video/filesize.php?imagewidth=1920&imageheight=1080&framerate=29.97&timeduration=60&timeunit=seconds)
* [calcul de bitrate](https://toolstud.io/video/bitrate.php?imagewidth=1&imageheight=1&colordepth=24&framerate=29.97)

## Formats de fichiers 

### Containers

| nom | extension |
| -	| -|
| QuickTime | .mov |
| Matroska  | .mkv |
| Mpeg4		| .mp4 |
| Windows Media Video | .wmv |
| Audio Video Interleaved | .avi |
| Theora 	| .ogv |

[wiki:Comparison_of_video_container_formats](https://en.wikipedia.org/wiki/Comparison_of_video_container_formats)

### Codecs

|Codec 				| compression		| usage 		|	 
| - 				|	-				|	 - 			|	
| H.264&VP8			|	intra & inter	| lecture<1080p 	|
| HEVC&VP9			|	intra & inter   | lecture<4k  	|
| proRes 			|	intra			| montage 		|
| dnxHD				|	intra 			| montage 		|
| HAP				|	intra 		 	| GPU&SSD   	 |

## Encodage vidéo
###  compression 

#### lossless/lossy

##### [Encodage vidéo sans perte - lossless](https://en.wikipedia.org/wiki/List_of_codecs#Lossless_video_compression)
* Apple Animation (QuickTime RLE)
* CinemaDNG Raw (Adobe, Blackmagic)
* séquence d'images (tiff, openexr)

##### [Encodage vidéo avec perte -lossy](https://en.wikipedia.org/wiki/List_of_codecs#Lossy_compression_2)
* H.264&VP8
* HEVC&VP9
* proRes, dnxHD, cineform		
* HAP & HAPQ	


#### intra/inter frame

##### intraframe
* Toute l'image individuellement compressée dans chaque image.
	* prores, dnxHD, photoJpeg, Apple intermediate codec (aic), cineform 	

##### [interframe](https://en.wikipedia.org/wiki/Inter_frame)
* image temporellement compressée, [ce qui change](http://dvd-hq.info/data_compression_3.php)
	* [images: I (clef), P (<-) et B(<->)](https://en.wikipedia.org/wiki/Video_compression_picture_types)
	* [GOP : group of picture](https://en.wikipedia.org/wiki/Inter_frame#/media/File:IPB_images_sequence.png)
* usage créatif [1](https://www.youtube.com/watch?v=rMSsw4CZvKg), [2](https://www.youtube.com/watch?v=rSmEOk5AiN0), [3](https://www.youtube.com/watch?v=dNa0-xrKi3Q)

### utilisation de FFmpeg
#### ex: Transcoder un fichier video vers un fichier prores compatible avec quicktime
```
ffmpeg -i INPUT.mkv -c:v prores_ks -profile:v 3 -c:a pcm_s16le -pix_fmt yuv420p OUTPUT.mov
```

Où `-profile` est un chiffre entire de -1 to 5 correspondant au profile prores suivant :

* -1: auto (default)
* 0: proxy ≈ 45Mbps YUV 4:2:2
* 1: lt ≈ 102Mbps YUV 4:2:2
* 2: standard ≈ 147Mbps YUV 4:2:2
* 3: hq ≈ 220Mbps YUV 4:2:2
* 4: 4444≈ 330Mbps YUVA 4:4:4:4
* 5: 4444xq ≈ 500Mbps YUVA 4:4:4:4

Où `-pix_fmt yuv420p` permet de créer un fichier compatible avec Quicktime

pour des usages réguliers voir : 

* FFmpeg Cookbook for Archivists [@kromer_FFmpegCookbookArchivists_2020]
* FFmpeg Cookbook par Greg Wessels [@wessels_FFmpegCookbook_2017]


pour des usages artistiques : 

* FFmpeg artschool [@associationofmovingimagearchivists_FFmpegArtschool_2020]

## Captation vidéo en temps réel 

## Logiciels de traitement vidéo en temps réel et d’interactivité 

## Logiciels de programmation nodale 

## Notions de traitement vidéo 
### Pixels
### Couleurs 
### Texture 
### Matrice 
### Mémoire tampon 
### Alpha channel 
### Rendu OpenGL