# Interagir {#interagir} 

## Lecture 
### Position
### Boucle
### Vitesse 
### Contrôler de la tête de lecture vidéo
### Montage temps réel 
### Gestion de banques d’images 

## Effets visuels et filtres applicables en temps réel sur des matériaux visuels  
## Flot de données entre les objets du logiciel 


## Utilisation d’interfaces de contrôle interactives {#interagir_interfaces}


## Communication via protocoles paramétriques temps réel {#interagir_protocoles} 

https://github.com/sebpiq/cours-son-reseaux/blob/main/applications-audio.md


### Open sound control (OSC) {#protocole_osc}
### Websocket {#protocole_websocket}
### MIDI {#protocole_midi}

### DMX {#protocole_dmx}
### ArtNet {#protocole_artnet}
     


* https://openframeworks.cc/ofBook/chapters/image_processing_computer_vision.html
* http://szeliski.org/Book/


## Usages de capture vidéo temps réel  



### Captation de mouvement et de présence

#### Théorie et survol 

* https://openframeworks.cc/ofBook/chapters/image_processing_computer_vision.html

##### Filtrage binaire

* http://what-when-how.com/introduction-to-video-and-image-processing/morphology-introduction-to-video-and-image-processing-part-1/
* http://what-when-how.com/introduction-to-video-and-image-processing/morphology-introduction-to-video-and-image-processing-part-2/

##### Blobs

* http://what-when-how.com/introduction-to-video-and-image-processing/blob-analysis-introduction-to-video-and-image-processing-part-1/



#### Mouvement {#interagir_mouvement}



* Différence de mouvement 
    * 


#### Présence {#interagir_presence}


* kinect

* p5js
    * https://www.tetoki.eu/vida/
    * https://github.com/orgicus/p5.js-cv

* Mediapipe (google)
    * https://github.com/google/mediapipe
    * https://github.com/cansik/mediapipe-osc
