# Exercices 

## Approbation du sujet pour le corpus vidéo {#formatif_1}
### Formatif

## Corpus vidéo {#sommatif_1}
### Sommatif 15% individuel
### Présentation orale individuelle de type partage d'écran de ~5 minutes
* Traiter une oeuvre et/ou une technique en lien avec le traitement vidéo  
* Partager un extrait court et des capture écran si approprié
* Présenter son contexte artistique et historique ainsi que les techniques et technologies employées 
* Sugérer une technique actuelle pour reproduire le résultat visuel
* Tenter de lier des [contenus essentiels](#contenus_essentiels) à la présentation  

## Présentation d'une question {#formatif_2}
### Formatif

## Question quiz {#sommatif_2}
### 10% individuel
### Rédaction d'une question pertinant et originale pour le quiz
* Rédaction d'une question théorique originale portant sur la matière du cours 
* Se référer aux [contenus essentiels](#contenus_essentiels)
* 4 choix de réponses éloquents comprenant la réponse


## Quiz théorique {#sommatif_3}
### 15% individuel
* formulaire en ligne à répondre individuellement
* Contient les questions quiz des deux groupes ainsi ceux de l'enseignement

##  Scènes vidéo  {#sommatif_4}
### 15% individuel
### Partage d'écran individuelle ~5 minutes
* Palette de 8 scène 
    * échantillons vidéo
    * caméra vidéo
    * source html
    * source nuancier
    * etc.


##  Mélangeur vidéo interactif {#sommatif_5}
### 15% individuel
### Partage d'écran individuelle ~5 minutes
* Variation temps réel des paramètres vidéo programmées


## Installation interactive et/ou performance audiovisuel{#sommatif_6}
### 25% individuel, équipe et classe.
### Présentation de type Flux(Stream) video de l'ensemble des projets  
où le traitement vidéo est effectué en temps réel 
* Présentation de type partage d'écran et stream simultané
* Changement de scène
* Changement de paramètres asservie
* Pourrait prendre la forme d'un VJ set via scènes dans OBS


